dataset: BCICIV2a+
data_path: 'data/BCICIV_2a_data_LR.h5'

num_subjects: 9
num_trials: 288
sub_order: [1, 2, 3, 4, 5, 6, 7, 8, 9]
batch_size: 32
train: true
epochs: 500
num_cv: 8
n_epochs_decay: 0
update_freq_t: 5

channels: 22
samples: 750
classes: 2

use_ddp: true
local_rank: ''
verbose: false

lr_G: 0.001
lr_D: 0.001
lr_policy: warmup
lr_decay_iters: 100
init_type: kaiming

outrm: true
min_samples: 5
proportion: 0.8
