dataset: OpenBMI
data_path: 'data/KU_mi_smt.h5'

num_subjects: 54
num_trials: 400
sub_order: [35, 47, 46, 37, 13, 27, 12, 32, 53, 54, 4, 40, 19, 41, 18, 42, 34, 7, 49, 9, 5, 48, 29, 15, 21, 17, 31,
                45, 1, 38, 51, 8, 11, 16, 28, 44, 24, 52, 3, 26, 39, 50, 6, 23, 2, 14, 25, 20, 10, 33, 22, 43, 36, 30]
batch_size: 64
train: true
epochs: 500
num_cv: 8
n_epochs_decay: 0
update_freq_t: 5

channels: 39
samples: 1000
classes: 2

use_ddp: true
local_rank: ''
verbose: false

lr_G: 0.001
lr_D: 0.001
lr_policy: warmup
lr_decay_iters: 100
init_type: kaiming

outrm: true
min_samples: 5
proportion: 0.8
